### ISSUE TITLE
URL incorreta para o manifesto de instalação

### ISSUE THREAD

**Issue by vkdolea** [coppolaop/cronicasrpg#42]
**Descreva o Bug**
O manifesto da versão publicada no FoundryVTT está incorreta e não é possível instalar pelo sistem.

**Para reproduzir**
Ir em "Install System" no FoundryVTT, selecionar o sistema Crônicas RPG e tentar instalar.

**Comportamento esperado**
Ao clicar, o sistema deveria instalar automaticamente

**Prints**
![image](https://user-images.githubusercontent.com/66521243/114961594-8071c500-9e3f-11eb-9f5e-380c933b54d2.png)

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Win10
 - A versão que você está utilizando do Sistema Crônicas RPG: 1.0.1

**Informações adicionais**
A URL do manifesto deveria ser o endereço RAW [exemplo certo: https://raw.githubusercontent.com/coppolaop/cronicasrpg/master/system.json] do arquivo system.json e não o endereço do arquivo system.json no resposiório [exemplo errado: https://github.com/coppolaop/cronicasrpg/blob/master/system.json].

**Comment by coppolaop** [comment]
Olá @vkdolea! Muito obrigado por avisar.
É a primeira vez que subo um pacote no Foundry.
Fiz a correção da URL, poderia validar, por favor?

**Comment by vkdolea** [comment]
Ainda dá erro. Criei PR com a proposta para adicionar a versão RAW do system.json no branch main.

**Comment by coppolaop** [comment]
Eu alterei direto no Foundry, esqueci que precisaria trocar aqui no Projeto tbm.
Ainda não chegou nenhum PR, chegando eu já aceito, gero outra versão e subo na ferramenta.
Eu deletei meu projeto local (onde desenvolvo), e baixei de novo pelo Foundry. Pareceu funcionar, mas deve ter algo pré-definido.

**Comment by vkdolea** [comment]
Digamos que eu esqueci de apertar um botão... E quanto a ter funcionado com o manifesto antigo, pode ser algo a predefinido ou então algum erro em minha máquina, não sei dizer ao certo :-(

Espero que dê tudo certo! :-)

**Comment by coppolaop** [comment]
Fechei a Issue com o Merge.
Testa, por favor, pra ver se agora a instalação funciona.
Se o erro persistir, comenta nessa issue mesmo que eu reabro ela.
