### ISSUE TITLE
Automação das Virtudes e defeitos

### ISSUE THREAD

**Issue by EstolanoBeu** [coppolaop/cronicasrpg#46]
Criar Automações nas virtudes que afetam diretamente as rolagens de dados, adicionando esses dados à rolagem.
Exemplo: [Atributo] Aprimorado, assinalar o uso tanto quanto seu gasto.

**Comment by coppolaop** [comment]
Eu cheguei a cogitar essa opção na criação inicial, porém existe um ponto importante que precisamos avaliar antes de implementar isso: A virtude de Atributo aprimorado só permite a melhoria 1 vez ao dia.
Em virtude disso optei por deixar sem automação.
Precisamos pensar em uma forma de ativação da habilidade, tem alguma ideia?

**Comment by coppolaop** [comment]
Analisei melhor a situação. Para atributos, especializações e movimentação, existem o campos "outros".
Acredito que a melhor solução para esse caso seria incrementar utilizando este campo.
Na issue #70 incluímos o calculo automático para vigor por ele não possuir essa opção de outros.
Caso prefira, você pode utilizar também shift+click para abrir uma caixa que permite inclusão de modificadores nas rolagens.
