### ISSUE TITLE
Espaço para virtudes na ficha melhorado.

### ISSUE THREAD

**Issue by EstolanoBeu** [coppolaop/cronicasrpg#47]
O espaço para virtudes na ficha de personagem é menor do que precisa ser. 
Normalmente um personagem não tem mais que uma ou duas virtudes, mas quando coloco duas virtudes com um título grande ou coloco uma terceira, aparece uma barra de rolagem sendo que há mais espaço na parte debaixo da ficha para ser usado.
![2021-05-14 (2)](https://user-images.githubusercontent.com/68084906/118337446-333e4d00-b4ea-11eb-9485-1c47b50e85e4.png)

**Comment by coppolaop** [comment]
Este bug está relacionado com o tamanho do texto. Adicionei vários de tamanho normal onde não houve quebra de linha e a barra de rolagem não apareceu. Ao adicionar um nome mais complexo, a quebra de linha é feita e a barra de rolagem é criada.
