### ISSUE TITLE
Pontos de Poder

### ISSUE THREAD

**Issue by jhorox** [coppolaop/cronicasrpg#61]
No sistema os magos ou herois usam pontos de poder como "mana" , porém nao encontrei na ficha.

Adoro o sistema e estarei sugerindo melhorias para o foundry... na minha opiniao o melhor sistema brasileiro é Cronicas.

Seria interessante ter um compendium do sistema mediante ao que tem no site.

**Comment by coppolaop** [comment]
Olá @jhorox
Vou incluir dois campos numéricos na aba de combate para "Pontos de poder livres" e "Pontos de poder totais".
Sobre o sistema em si, gosto muito da mecânica dele também e agradeço muito pelas sugestões.
A questão do compêndio é um interesse meu também, mas vou precisar de um tempo para conseguir desenvolver.
Minha intenção é adicionar um compendio de regras, monstros/animais e fichas prontas de NPCs do livro, mas ainda não tenho previsão de quando vou conseguir fazer.
