### ISSUE TITLE
Bugou a ficha

### ISSUE THREAD

**Issue by jhorox** [coppolaop/cronicasrpg#66]
Ficou toda zuada a ficha alguma coisa aconteceu.

![Screenshot_1](https://user-images.githubusercontent.com/28152858/148600411-d5023aef-17dc-4189-889d-e79429a9cb1d.png)

**Comment by coppolaop** [comment]
Eu vi algo parecido acontecer com o outro sistema q eu fiz (Cordel do Sol Encantado) mas ainda não sei identificar o problema.
Consegue me trazer mais informações?
- Isso acontece sempre?
- Já reiniciou o foundry?
- Uso local ou em núvem?
- Acontece com todos os jogadores?
- Já tentou reinstalar/Atualizar o Crônicas nele?
- Já tentou desabilitar os módulos q vc usa pra ver se funciona?
Quanto mais informação vc tiver, melhor pra acharmos o problema.
Desculpa pela demora, eu demoro pra perceber as notificações do Github, mas vou procurar ver como posso melhorar isso.

**Comment by coppolaop** [comment]
Resolvido ajustando o Foundry para idioma em português.
